In [1]:
import numpy as np

In [2]:
cn= np.array([[1,0,0,0],
     [0,1,0,0],
     [0,0,0,1],
     [0,0,1,0]])
cnn= np.array([[1,0,0,0],
     [0,0,0,1],
     [0,0,1,0],
     [0,1,0,0]])
h=np.array([[1,1],[1,-1]])
I= np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
bit= np.array([[-1],[0],[0],[-1],[-1],[0],[0],[-1]])

In [5]:
np.linalg.inv(I)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
print(cn)
print(cnn)
print(I)
print(bit)
print(h)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[-1]
 [ 0]
 [ 0]
 [-1]
 [-1]
 [ 0]
 [ 0]
 [-1]]
[[ 1  1]
 [ 1 -1]]


In [4]:
hh=np.kron(h,I)
hhh=np.kron(hh,I)

print(hh)
print(hhh)

[[ 1  0  1  0]
 [ 0  1  0  1]
 [ 1  0 -1  0]
 [ 0  1  0 -1]]
[[ 1  0  0  0  1  0  0  0]
 [ 0  1  0  0  0  1  0  0]
 [ 0  0  1  0  0  0  1  0]
 [ 0  0  0  1  0  0  0  1]
 [ 1  0  0  0 -1  0  0  0]
 [ 0  1  0  0  0 -1  0  0]
 [ 0  0  1  0  0  0 -1  0]
 [ 0  0  0  1  0  0  0 -1]]


In [60]:
hh.dot(bit)

array([[1],
       [0],
       [1],
       [0]])

In [5]:
a=np.kron(cn,I)
print(a)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]


In [6]:
phi=a.dot(bit)
print(phi)

[[-1]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [-1]
 [-1]
 [ 0]]


In [7]:
b=np.kron(cnn,I)
print(b)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


In [8]:
phiA=b.dot(phi)
print(phiA)

[[-1]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [-1]]


In [9]:
phiAa=a.dot(phiA)
print(phiAa)

[[-1]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [-1]]


In [10]:
phiAb=b.dot(phiAa)
print(phiAb)

[[-1]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [-1]
 [-1]
 [ 0]]


In [11]:
phiAc=b.dot(phiAb)
print(phiAc)

[[-1]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [-1]]


In [12]:
phiAd=b.dot(phiAc)
print(phiAd)

[[-1]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [-1]
 [-1]
 [ 0]]


In [13]:
phiB = hhh.dot(phiAd)
print(phiB)

[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [-1]]


In [43]:
c=a.dot(bit)
print(c)

[[1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]]


In [46]:
d=b.dot(c)
print(d)

[[1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]]


In [50]:
e=b.dot(d)
print(e)

[[1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]]


In [52]:
f=b.dot(e)
print(f)

[[1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]]


In [54]:
g=hhh.dot(f)
print(g)

[[ 1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]]


In [14]:
np.sqrt(3+1j)

(1.755317301824428+0.28484878459314106j)